### ISSUE TITLE
Active Drop Down Menu Items Fire Functions

### ISSUE THREAD

**Issue by justinsrd** [justinsrd/stat_tracker#12]
Hey so if the drop down menu has a list of all the different stats to display, can they be made to fire off a function when they are selected?

**Comment by lmcnern** [comment]
For reference, I have a drop down menu here: https://github.com/lmcnern/stat_tracker/blob/dropDownMenu/dropDown.html

It fires a test function with the event onchange, which works when tied to the select element, but not when tied to the options one. So when you start working on this, you don't need to start from the beginning.

**Comment by mskalandunas** [comment]
Done with most recent push.
